"""Case-file / SAR export — a printable, self-contained investigation report
for a single alert (entity, verdict, SHAP drivers, notes, disposition)."""
import html
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse

from auth import verify_token
from database import db

router = APIRouter()


def _row(label: str, value: str) -> str:
    return (f'<tr><td class="k">{html.escape(label)}</td>'
            f'<td class="v">{value}</td></tr>')


@router.get("/v1/alerts/{alert_id}/report", response_class=HTMLResponse)
async def case_report(alert_id: str, user: dict = Depends(verify_token)):
    alert = db.get_alert(alert_id) if db.DB_ENABLED else None
    if not alert:
        raise HTTPException(status_code=404, detail="alert not found")
    notes = db.list_notes(alert_id) if db.DB_ENABLED else []
    feedback = db.feedback_for(alert_id) if db.DB_ENABLED else []
    shap = alert.get("shap_json") or {}

    score = float(alert.get("risk_score") or 0)
    label = alert.get("risk_label", "SAFE")
    label_color = {"FRAUD": "#c0392b", "SUSPICIOUS": "#b7791f", "SAFE": "#2f7a3a"}.get(label, "#555")

    shap_rows = "".join(
        f'<tr><td class="k">{html.escape(str(k))}</td>'
        f'<td class="v" style="font-family:monospace">{v:+.4f}</td></tr>'
        for k, v in shap.items() if not str(k).startswith("_")
    ) or '<tr><td colspan="2" class="muted">No SHAP attribution stored.</td></tr>'

    notes_html = "".join(
        f'<li><span class="muted">{html.escape(n["created_at"])} · '
        f'{html.escape(n["author"])}</span><br>{html.escape(n["body"])}</li>'
        for n in notes
    ) or '<li class="muted">No investigator notes.</li>'

    disp = feedback[0]["label"].replace("_", " ") if feedback else "—"

    fv = alert.get("feature_vector") or [0, 0, 0, 0, 0]
    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<title>VaultStream Case File · {html.escape(alert_id[:12])}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; color:#1a1a1a;
         max-width: 760px; margin: 40px auto; padding: 0 24px; line-height: 1.5; }}
  h1 {{ font-size: 22px; margin: 0 0 2px; }}
  .sub {{ color:#888; font-size: 13px; margin-bottom: 24px; }}
  .verdict {{ display:inline-block; padding:6px 14px; border-radius:999px; color:#fff;
             font-weight:700; font-size:13px; background:{label_color}; }}
  h2 {{ font-size: 14px; text-transform: uppercase; letter-spacing: .08em; color:#666;
        border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; margin: 28px 0 12px; }}
  table {{ width:100%; border-collapse: collapse; font-size: 14px; }}
  td {{ padding: 6px 4px; vertical-align: top; border-bottom: 1px solid #f0f0f0; }}
  td.k {{ color:#777; width: 200px; }}
  td.v {{ font-weight: 500; }}
  ul {{ padding-left: 18px; }} li {{ margin-bottom: 10px; font-size: 14px; }}
  .muted {{ color:#aaa; }}
  .foot {{ margin-top: 40px; font-size: 11px; color:#bbb; border-top:1px solid #eee; padding-top:12px; }}
  @media print {{ body {{ margin: 0; }} .noprint {{ display:none; }} }}
</style></head><body>
<button class="noprint" onclick="window.print()"
  style="float:right;padding:8px 16px;border:1px solid #ccc;border-radius:8px;background:#fff;cursor:pointer">
  Print / Save PDF</button>
<h1>Suspicious Activity Case File</h1>
<div class="sub">VaultStream · generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
  by {html.escape(user.get('email', 'analyst'))}</div>
<p><span class="verdict">{html.escape(label)} · {round(score*100,1)}% risk</span></p>

<h2>Transaction</h2>
<table>
  {_row("Alert ID", html.escape(alert_id))}
  {_row("Transaction ID", html.escape(str(alert.get('transaction_id', '—'))))}
  {_row("Entity", html.escape(str(alert.get('entity_id', '—'))))}
  {_row("Detected at", html.escape(str(alert.get('created_at', '—'))))}
  {_row("Case status", html.escape(str(alert.get('status', 'open'))))}
  {_row("Assignee", html.escape(str(alert.get('assignee') or '—')))}
  {_row("Action taken", html.escape(str(alert.get('action_taken') or '—')))}
  {_row("Analyst disposition", html.escape(disp))}
</table>

<h2>Behavioural features</h2>
<table>
  {_row("Tx count · 5m", str(fv[0]))}
  {_row("Tx count · 1h", str(fv[1]))}
  {_row("Tx count · 24h", str(fv[2]))}
  {_row("Sum amount · 1h", f"${float(fv[3]):,.2f}")}
  {_row("Device shift", "yes" if fv[4] else "no")}
</table>

<h2>Model attribution (SHAP)</h2>
<table>{shap_rows}</table>

<h2>Investigator notes</h2>
<ul>{notes_html}</ul>

<div class="foot">Confidential — generated by VaultStream for internal investigation
and regulatory reporting. Pseudonymised demo data.</div>
</body></html>"""
    return HTMLResponse(content=doc)
